language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle test:scalastyle coverage test doc test:doc
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coveralls

